### ISSUE TITLE
Make worldPing plugin provisionable

### ISSUE THREAD

**Issue by walterdolce** [raintank/worldping-app#213]
It appears that at the moment it's not possible to let Grafana automatically provision the configuration of the plugin at install time the same way one would do with datasources.

As it *is* possible to automate the provisioning of the Azure Monitor plugin, I was wondering why users _have to_ install the plugin manually (this step can be easily automated) *and* go through the Grafana UI to add the API key, etc to enable it?

So far I tried the following but it didn't work. I still had to go through the UI and sort this out manually, which nowadays is arguably not a good thing.
```
# ... other datasources config...
- name: worldPing - local
  type: raintank-worldping-app
  access: proxy
  enabled: true
  pinned: true
  jsonData:
    apiKeySet: true
  secureJsonData:
    apiKey: the-api-key
```

Thank you.
